name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile and test
        run: |
          cd tests
          javac SimpleProgramme.java
          

      - name: Upload test results artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/test-output
