name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download JSONPath JAR
        run: |
          mkdir -p libs
          wget -O libs/json-path-2.6.0.jar https://repo1.maven.org/maven2/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar

      - name: Compile and test
        run: |
          mkdir -p classes
          javac -cp libs/json-path-2.6.0.jar -d classes tests/SimpleProgramme.java
          java -cp libs/json-path-2.6.0.jar:classes SimpleProgramme

      - name: Upload test results artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/test-output
